### ISSUE TITLE
How to access the original logic.defaults?

### ISSUE THREAD

**Issue by kairyu** [keajs/kea-localstorage#14]
Thank you for the great plugin again!

Recently I have a use case which needs to access the original `logic.defaults` while `kea-localstorage` plugin is enabled.

From my understanding, `kea-localstorage` will override the original `defaults` with the values in localStorage when the values has option `{ permit: true }`. Is there any way to access the original `defaults` in this case?

If there is no existing way to access it, could you please consider to add a new feature such as changing the mechanism to avoid overriding the `defaults` or copying the original `defaults` to another property e.g. `originalDetaults` before this plugin override them?

Thank you in advance.

**Comment by mariusandra** [comment]
Hey!
Sure, it's out now in `1.0.2`. You can use `logic.cache.localStorageDefaults['reducerKey']` to get the original default for `reducerKey`

**Comment by kairyu** [comment]
I'm sorry for not getting back to this issue sooner. You are amazing! I really appreciate for you prompt improvement!

**Comment by mariusandra** [comment]
No problem :).

One more thing though, you might be interested in the new [babel-plugin-kea](https://kea-docs.netlify.app/docs/guide/debugging), which automatically adds `path`s to logic that doesn't have any manually defined. It might save some typing.

**Comment by kairyu** [comment]
Oh that's good to know. Really cool stuff! Let me try it.
