### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by marciobueno1** [keajs/kea-localstorage#2]
**First of all:** congratulation for you good work with all kea libraries.

**Question:** Will this plugin support React-Native? Using AsyncStorage instead of window.storage?

**Comment by marciobueno1** [comment]
Well, manually creating the store (without using getStore()), it was easy to integrate with [redux-persist](https://github.com/rt2zz/redux-persist).

**Comment by mariusandra** [comment]
Closing this old issue :).

You can now use `storageEngine` when configuring the kea localstorage plugin to replace `window.localStorage` with whatever.
