### ISSUE TITLE
Keajs 2.4  "kea.inline" hard coded.

### ISSUE THREAD

**Issue by volkandkaya** [keajs/kea-localstorage#27]
After reading the 2.4 keajs blog post I noticed it talks about "kea.inline" hard coded

https://github.com/keajs/kea-localstorage/blob/master/src/index.js#L54

**Comment by mariusandra** [comment]
Oh, apologies, I forgot to push the changes, but 1.1.1 of kea-localstorage checks for `kea.logic` instead of `kea.inline`
